package com.example.audiocutter.functions.mystudio

object Constance {

    val ACTION_UNCHECK = "ACTION_UNCHECK"
    val ACTION_HIDE = "ACTION_HIDE"
    val ACTION_DELETE_ALL = "ACTION_DELETE_ALL"
    val ACTION_STOP_MUSIC = "STOP_MUSIC"
    val ACTION_CHECK_DELETE = "ACTION_CHECK_DELETE"
    val ACTION_DELETE = "ACTION_DELETE"
    val ACTION_CANCEL = "ACTION_CANCEL"

    val TYPE_AUDIO_TO_NOTIFICATION = "TYPE_AUDIO_TO_NOTIFICATION"
    val TIME_LIFE_DEFAULT = "00:00"
    val TIME_TOTAL_DEFAULT = "/00:00"
    val RINGTONE_TYPE = 0
    val ALARM_TYPE = 1
    val NOTIFICATION_TYPE = 2

    val AUDIO_CUTTER = 0
    val AUDIO_MERGER = 1
    val AUDIO_MIXER = 2

    val AUDIO_CUTTER_STRING = "Audio Cutter"
    val AUDIO_MERGER_STRING = "Audio Merger"
    val AUDIO_MIXER_STRING = "Audio Mixer"

    val TYPE_RESULT = "TYPE_RESULT"
    val TYPE_AUDIO = "TYPE_AUDIO"
    val NOTIFICATION_ACTION_EDITOR = "NOTIFICATION_ACTION_EDITOR"
}