package com.example.a0025antivirusapplockclean.base.viewstate

enum class ViewStateScreen {
    HOME_SCREEN,
    LIST_CONTACT_SCREEN,
    MP3_CUT_CHOOSER_SCREEN,
    MP3_MERGE_CHOOSER_SCREEN,
    MP3_MIX_CHOOSER_SCREEN,
    MIXING_EDITOR_SCREEN,
    LIST_CONTACT_CHOOSER_SCREEN,
    MY_STUDIO_SCREEN,
    CUTTING_EDITOR_SCREEN,
    MERGING_EDITOR_SCREEN,
    RESULT_SCREEN,
    SET_CONTACT_SCREEN,
    SETTING_SCREEN,
    APP_CHOOSER_SCREEN,
    FLASH_CALL_SCREEN,
    INTRODUCTION_1,
    INTRODUCTION_2,
    INTRODUCTION_3,
    SPLASH

}